### ISSUE TITLE
Support Partitioned DML

### ISSUE THREAD

**Issue by yfuruyama** [cloudspannerecosystem/spanner-cli#93]
Cloud Spanner has two execution modes for DML, DML and [Partitioned DML](https://cloud.google.com/spanner/docs/dml-partitioned), but currently spanner-cli only supports normal DML. It would be better to support Partitioned DML in spanner-cli since it can process large-scale operations over the entire rows.

One thing we might need to discuss would be syntax for executing a Partitioned DML.

Context: https://github.com/cloudspannerecosystem/spanner-cli/pull/92#issuecomment-710775585

**Comment by yfuruyama** [comment]
@apstndb You mentioned `EXECUTE PARTITIONED (INSERT|UPDATE|DELETE) ...` as an example for the syntax in https://github.com/cloudspannerecosystem/spanner-cli/pull/92#issuecomment-710775585, but what is the rationale behind it?

I'm wondering if we can make it simpler by just saying `PARTITIONED (INSERT|UPDATE|DELETE) ...` to indicate executing the DML as a Partitioned DML.

**Comment by apstndb** [comment]
`EXECUTE PARTITIONED (INSERT|UPDATE|DELETE)` is inspired by `EXECUTE IMMEDIATE` but only for example and no rationale.
It may be even wrong because of ambiguous syntax with the standard Dynamic SQL(`EXECUTE IMMEDIATE`, `PREPARE` and `EXECUTE`).

I want to vote `PARTITIONED (INSERT|UPDATE|DELETE) ...` because it is simple and unambiguous.

**Comment by yfuruyama** [comment]
Sounds good, then let's use `PARTITIONED (INSERT|UPDATE|DELETE) ...` for the syntax. I'll take on this.
